### ISSUE TITLE
Настроить вид графика комментариев

### ISSUE THREAD

**Issue by iprst** [audetv/fct-search#100]
> Нету ни в какой теме, ни в каком браузере. График пропал **до** подключения тёмного оформления. 
> https://fct-search.audetv.ru/svodd

График появился, но требует оформления в новых цветах обоих шаблонов.

**Comment by audetv** [comment]
После деплоя новой сборки, пересобираются и файлы стилей и скрипты, и бывает, что браузер не сразу кэш обновляет и не стразу на обоих сервисах обновляются файлы стилей, поэтому есть момент, когда слетают все стили и скрипты, позже происходит их генерация и все становиться нормально. Я пока не знаю, что с этим делать. Т.е. решение есть, но пока оно меня не устраивает и ранее, я ранее сам после деплоя прокликивал страницы для генерации, и я думаю поэтому вы не попадали на этот эффект. 
У меня сейчас график работает.

**Comment by iprst** [comment]
Да, график работает. Мне нужно отредактировать его цвета, я так понимаю он подключается через канвас и его стили лежат где-то отдельно. 

Также обновил шаблон тёмной темы, доработано всё недоработанное ранее.

**Comment by audetv** [comment]
Да стили внутри JS, у графика нет своих стилей, в файлах css. Надо правит в секциях виджета тут: с 82 по 187 строки файла: app/frontend/views/svodd/index.php но так просто в лоб не получится, я думаю, так как надо, определять какая тема сейчас подключена и от этого должны ставиться нужные цвета, в общем условия надо прописать, я займусь. можно по цветам пока определиться, какие предложения?

**Comment by iprst** [comment]
По цветам надо просто — график оформить так, чтобы он а обеих схемах отрисовывался одними цветами. То есть нужно убирать альфу у элементов, которые прозрачны, например у `'data' => $datasetFct,` должен быть просто цвет посередине между светлым фоном и тёмным фоном. Сейчас поковыряю.

**Comment by iprst** [comment]
Так. Что-то я проапдейтил цвета в виджете [app/frontend/views/svodd/index.php](https://github.com/audetv/fct-search/blob/main/app/frontend/views/svodd/index.php), но изменений не вижу, видимо что-то где-то нужно «прокликивать» вручную.  

Независимый от темы оформления «красный график СВОДД»
```
'data' => $datasetSvodd,
…
'backgroundColor' => 'rgba(114, 10, 10, 1)',
'borderColor' => 'rgba(88, 10, 10, 1)',
```

Независимый от темы оформления «серый график ФКТ»
```
'data' => $datasetFct,
…
'backgroundColor' => 'rgba(80, 79, 79, 1)',
'borderColor' => 'rgba(54, 52, 52, 1)',
```

В обоих лейблах текст белый `white`

Осталось добавить единственное условие — цвет шрифта текста «темы с даты по дату», что-то вроде:
```
light = 'rgba(33, 37, 41, 1)',
dark = 'rgba(191, 195, 195, 1)',
```
Это же условие цветов для легенды лейблов и для текста «текущий процент / общий процент».

**Comment by iprst** [comment]
> В обоих лейблах текст белый `white`

Нет, это зря. Слишком ядрёно в тёмной теме. 
В светлой нужно оставить белый, а в тёмной сделать `dark = 'rgba(191, 195, 195, 1)'`

**Comment by audetv** [comment]
Да, я сейчас пишу функцию, которая будет забирать значение темы из store браузера и от значения выводить цвет.

**Comment by audetv** [comment]
Возможно. Пока не знаю, надо будет в доках посмотреть. Посмотрю в документации.

**Comment by iprst** [comment]
> В планах посмотреть: How to Implement Dark Mode in Chart JS
> https://www.youtube.com/watch?v=NV-8--_w1wY

Посмотрел видео. Основная сложность в иерархии файлов и том, как быстро разобраться где что находится.

**Comment by iprst** [comment]
Всё работает как предполагалось. В последствии, если потребуется, цветовую схему можно будет откорректировать, но вопрос переключения закрываем.
