### ISSUE TITLE
Фильтр или поиск по дате комментария

### ISSUE THREAD

**Issue by iprst** [audetv/fct-search#123]
Фильтр даты — чекбокс. 
Поиск по дате — радиокнопка. 

Дату вводить или окошком, или календарём, или не вводить, а забирать из строки поиска.

**Comment by audetv** [comment]
Фильтр по дате, хорошо. Тем более, что реализация этого механизма пересекается с идеей по графику курса. 
Получить формализованные данные из календаря или отдельной строки ввода даты, выглядит проще, чем разбирать поисковую строку запроса, я имею ввиду если в строке не соблюдать правила ввода даты. Попробуем для начала с календарем. 
Т.к. механизм фильтра по дате будет реализован независимо от формы ввода даты, то над самой формой ввода данных можно поработать отдельно, поисковая строка, календарь или еще что-то. Т.е. это уже немного другая задача. Принято.

Надо поставить в разработку. Похоже уже надо составить публичный план разработки (дорожную карту) пронумерованный список.

**Comment by iprst** [comment]
> надо составить публичный план разработки (дорожную карту) пронумерованный список

В проектах есть представление Roadmap:

![image](https://user-images.githubusercontent.com/129882753/233767951-3e45cd60-716f-4a8c-917a-f35c5096480f.png)

**Comment by audetv** [comment]
Просьба посмотреть, какой фильтр нам подходит лучше из этих
https://demos.krajee.com/date-range#usage

**Comment by iprst** [comment]
Смотреть надо с учётом #61 «Динамический график USD/RUB + ФКТ/СВОДД + Список комментариев»?

**Comment by iprst** [comment]
> Date and Time picker with time increment of 15 minutes and without any input group addons.

Этот вариант в принципе неплохо уживается с будущим подключением графика USD/RUB, но сам метод ввода не очень удобен. 

> DateRangePicker in a dropdown format (uneditable/hidden input) and uses the preset dropdown.

Этот вариант хорош тем что он достаточно стандартен, а если его можно перевести на русский то вообще замечательно.

**Comment by audetv** [comment]
> Смотреть надо с учётом #61 «Динамический график USD/RUB + ФКТ/СВОДД + Список комментариев»?

Я думаю нет, это не обязательно, виды фильтров могут быть разными, сам алгоритм на сервере будет единым, запрос из бд и предоставление данных, а как это в интерфейсе, мы можем определять независимо. В поиске свой фильтр, в графике свой вид.

> Этот вариант хорош тем что он достаточно стандартен, а если его можно перевести на русский то вообще замечательно.

Да, плагин можно на русский перевести, есть подключение файлов локали, с этим все нормально и формат дат изменить тоже можно.

**Comment by iprst** [comment]
Значит берём его.

**Comment by iprst** [comment]
Если в календаре не выбрана дата, то окошко не должно быть пустым, ибо не понятно, что это за окошко. В окошке должно быть написано «За весь период». 

[Покрасил](https://github.com/audetv/fct-search/pull/170) форму ввода календаря чтобы она отличалась от формы ввода поисковой строки. Теперь, если пустоту заменим на текст «За весь период», то всё будет наглядно.

**Comment by audetv** [comment]
> Если в календаре не выбрана дата, то окошко не должно быть пустым, ибо не понятно, что это за окошко. В окошке должно быть написано «За весь период».

Добавил placeholder #171 
И сместил влево тест в поле ввода, чтобы визуально на одной линии были с поиском

**Comment by iprst** [comment]
Кажется поиск работает как должно. Надо закрывать issue по поиску, а дальнейшие движения по прикручиванию к фильтру по датам графика USD/RUB выполнять в рамках нового issue когда придёт время.
