### ISSUE TITLE
Приобрести домен для поисковика

### ISSUE THREAD

**Issue by iprst** [audetv/fct-search#132]
Хотел приобрести домены, но подумал что в данный момент лучше если это сделает @audetv поскольку он уже администрирует свой текущий, на котором временно расположен поисковик. Кроме того это логичнее дабы не возникали сложности с правами собственности и прочего административного оформления в случае переноса хостинга и подобных работ. 

Сейчас для регистрации доступен внимание!
### [svodd.ru](https://beget.com/ru/domains/search/svodd) 

Надо брать и закрывать вопрос. 
Этот же домен можно использовать для сокращения ссылок на любую динамическую страницу. 

ПС. Вот [здесь](https://jino.ru/domains/price/.ru/) домен в зоне .ru можно купить за 39 рублей, а перед продлением перевести на обслуживание в любой другой регистратор бесплатно.

**Comment by audetv** [comment]
Оформил регистрацию SVODD.RU Услугу оплатил, домен в процессе регистрации.

**Comment by audetv** [comment]
> Думаю, нужно поменять на более говорящее название страницы. Например https://svodd.ru/graph

Да, хорошо, логично.

название bolshaya-svoddnaya-tema оставляем?

**Comment by iprst** [comment]
> название bolshaya-svoddnaya-tema оставляем?

Наверное да? Лично у меня есть неудовольствие при использовании транслита, но с другой стороны он часто используется при генерации имён страниц в сети из заголовка страницы или текста на ней, поэтому пусть так. Это очевидно лучше, чем кракозябры, получаемые в текущий момент из кириллицы, и одновременно нет англофилии.

**Comment by iprst** [comment]
Ru-center уже обновил и теперь отдаёт табличку 

```
Сайт svodd.ru не опубликован
Если здесь должен был быть ваш сайт, 
опубликуйте его в панели управления.
```

**Comment by audetv** [comment]
Произведен перенос сайта на новый домен https://svodd.ru
Ведутся работы по настройке пересылки со старого домена fct-search.audetv.ru на новый домен svodd.ru
Спасибо за понимание.

**Comment by iprst** [comment]
Поздравляю! Ура!
