### ISSUE TITLE
Индексирование сайта поисковыми системами не работает.

### ISSUE THREAD

**Issue by audetv** [audetv/fct-search#150]
До этого момента и сейчас в настройках сайта в файле https://svodd.ru/robots.txt
установлен запрет на обход и индексирование сайта для всех поисковых систем. 
`User-agent: * Disallow: /`
Как считаете стоит ли уже включить индексирование? Домен поменяли, сервис развивается.

**Comment by iprst** [comment]
А что в нашем случае даёт индексирование в поисковиках?

**Comment by audetv** [comment]
Разгерметизацию, видимость в поиске, если нас будут искать, чтобы сайт можно было найти в поиске yandex, google.
Сейчас это выглядит в яндексе так
![2023-04-26_13-35-09](https://user-images.githubusercontent.com/10896447/234550267-5c070a02-2551-436d-a3d7-40c97e2230bb.png)
Это можно увидеть в яндексе, если ввести в поиск домен, а в гугле вообще нет записей в выдаче, даже по домену

Что будет после того как сайт будет проиндексирован, я не знаю. Возможно будет больше трафик на поисковик, сейчас трафик только с ФКТ и прямые заходы от тех ,кто знает. Возможно забанят, но врятли. Возможно о нас узнает больше людей.

**Comment by iprst** [comment]
Если говорить чисто о поисковике, то по какой причине возникнет сторонний трафик? Ведь это поисковик по конкретному сайту, по сути в текущий момент по комментариями одного сайта. В текущем виде он может быть интересен только пользователям ФКТ, и это нормально. 

Если робот.тхт будет открыт для поисковых систем, ну допустим проиндексируется тема СВОДД и результаты будут в выдаче скажем яндекса и гугла. Давайте в уме или на бумажке смоделируем такую ситуацию, что поисковики найдут в комментариях? 

Можно зайти по-другому — что поисковики находят _сейчас_ в комментариях самого ФКТ? Контент то у нас, условно идентичный.

**Comment by audetv** [comment]
> Если говорить чисто о поисковике, то по какой причине возникнет сторонний трафик? 

Думаю, это будут прямы заходы или переходы по ссылкам, но вполне возможно, что еще и по причине загуглить поисковик в яндексе, описал ниже историю, например если человек перейдет по ссылке и позже захочет вернуться на сайт, то может загуглить в яндексе, при условии, что хотя бы помнит имя домена или название сайта.

> Давайте в уме или на бумажке смоделируем такую ситуацию, что поисковики найдут в комментариях?

Цитаты из новостей и простыню какого-то текста, не размеченного заголовками <H>, разделенного на страницы и нарушающего все методички SEO. Скорее всего присвоят мусорный рейтинг и поставят в график обхода роботом раз в месяц =)

> Можно зайти по-другому — что поисковики находят сейчас в комментариях самого ФКТ? Контент то у нас, условно идентичный.

Да, контент идентичный. Я не знаю что поисковики находят в комментариях ФКТ. Можно конечно провести анализ, и по каким либо фразам поискать, индексируют ли они вообще. 

Я считаю, нет смысла продвигать какие-то комментарии в поиске, или какие-то вопросы, а кроме этого больше ничего на сайте нет. Т.е. я вообще, совсем, не хочу заниматься каким любо специальным продвижением сайта по методичкам SEO.

Открытие сайта для индексации даст лишь то, что сайт можно будет найти по названию домена. 
 
В своей деятельности неоднократно наблюдал, как люди набирают название домена или части домена, или имя сайта, если оно запоминается, в поисковой строке поисковика yandex. И вот прямо некоторые в яндексе набирают google и переходят на него по ссылке из выдачи) Это забавно, но я такое видел неоднократно. 

Я не ожидаю трафик на сайт, мой вопрос не преследует эту цель. Более того я намерено скрыл сайт из выдачи, по причинам, что разработка, что сервис окажется не востребованным. Возможно сейчас момент изменился. Делюсь мыслями. 

Стоит поизучать то поисковики находят сейчас в комментариях самого ФКТ?

**Comment by iprst** [comment]
> Я не знаю что поисковики находят в комментариях ФКТ. Можно конечно провести анализ, и по каким либо фразам поискать, индексируют ли они вообще.

Я до появления нашего поисковика пользовался яндексом с подключением в запрос site:фкт-алтай.рф — это работало какое-то время, но после того как яндекс продали какой-то левой конторе, поиск по доменам стал сопровождаться капчей на каждой странице, а домены перестали индексироваться и найти что-либо стало невозможно. 

https://фкт-алтай.рф/robots.txt

```
User-agent: SemrushBot
Disallow: /

User-agent: Yandex
Host: fct-altai.ru
Crawl-delay: 2
Disallow:

User-agent: *
Disallow:
```

> Я считаю, нет смысла продвигать какие-то комментарии в поиске, или какие-то вопросы, а кроме этого больше ничего на сайте нет. Т.е. я вообще, совсем, не хочу заниматься каким любо специальным продвижением сайта по методичкам SEO.

Это понятно. 

> Открытие сайта для индексации даст лишь то, что сайт можно будет найти по названию домена.
> 
> В своей деятельности неоднократно наблюдал, как люди набирают название домена или части домена, или имя сайта, если оно запоминается, в поисковой строке поисковика yandex. И вот прямо некоторые в яндексе набирают google и переходят на него по ссылке из выдачи) Это забавно, но я такое видел неоднократно.

Я видел такой сценарий, он не служит аргументом: если человек воспользуется яндексом, то сейчас яндекс находит fct-search.audetv.ru и по ссылке можно перейти, домен svodd.ru пока не находит, но видимо будет. Гугл вообще ничего не находит, но если поисковик не даст результата, догадается ли клиент, что нужно воспользоваться адресной строкой?

**Comment by audetv** [comment]
[Комментарий 43827](https://svodd.ru/?search%5Bquery%5D=432827&search%5Bmatching%5D=&search%5Bmatching%5D=in&search%5Bdictionary%5D=0
) 2 темы назад , более месяца.
Ввел целиком фразу в яндексе:
27 июля 1990 года была принята Декларация Верховного Совета «О государственном суверенитете Республики Беларусь».

Не нашел в поиске фкт. Думаю, комментарии не индексируются )

**Comment by iprst** [comment]
> Не нашел в поиске фкт. Думаю, комментарии не индексируются )

Поиск по ним можно было проводить, и я этим пользовался постоянно. Пруф: 
https://svodd.ru/?search%5Bquery%5D=https%3A%2F%2Fyandex.ru%2Fsearch%2F%3Ftext%3D&search%5Bmatching%5D=&search%5Bmatching%5D=query_string&search%5Bdictionary%5D=0

**Comment by audetv** [comment]
>  Гугл вообще ничего не находит, но если поисковик не даст результата, догадается ли клиент, что нужно воспользоваться адресной строкой?

Обычно после этого следует звонок в тех поддержку) Не знаю, клиенту придется выйти из режима автопилота и включить голову. Хорошо же.

> Я до появления нашего поисковика пользовался яндексом с подключением в запрос site:фкт-алтай.рф

Я имел ввиду совсем простой сценарий https://yandex.ru/search/?text=fct-altai.ru&lr=2 прямо вот, чтобы просто на сайт фкт попасть. 


> Поиск по ним можно было проводить, и я этим пользовался постоянно. Пруф:

Наш поиск больше результатов выдает на «велесова книга». Так что яндекс нас точно  забаит нас в выдаче)

В общем, наверно, в текущем моменте оставляем как было. Так?

**Comment by audetv** [comment]
> Гугл вообще ничего не находит, но если поисковик не даст результата, догадается ли клиент, что нужно воспользоваться адресной строкой?
И еще момент, сейчас заметил, решил провести эксперимент, Предполжим клиент догадался и набрал в адреснной строке, но обычно браузеры устанавливают туда поиск, т.е. это строка работает как запрос в поисковик, и если не поставить слэш, косую черту после домена, то клиент попадет опять в выдачу яндекс, гугл, в которых ничего нет. Забавно.

**Comment by iprst** [comment]
> браузеры устанавливают туда поиск, т.е. это строка работает как запрос в поисковик, и если не поставить слэш, косую черту после домена, то клиент попадет опять в выдачу яндекс, гугл, в которых ничего нет

В хроме такое поведение не воспроизводится. С чистого аккаунта, незнакомого с сайтом: 

![chrome_ZvviA99gbb](https://user-images.githubusercontent.com/129882753/234571620-37687b0a-1859-4bb4-b9e7-593236a1fedb.gif)

**Comment by iprst** [comment]
> Я имел ввиду совсем простой сценарий https://yandex.ru/search/?text=fct-altai.ru&lr=2 прямо вот, чтобы просто на сайт фкт попасть.

Нет, я отвечал на другую фразу: 

> Я не знаю что поисковики находят в комментариях ФКТ. Можно конечно провести анализ, и по каким либо фразам поискать, индексируют ли они вообще.

Индексируют, поскольку можно было проводить поиск по тексту комментария и я этим пользовался постоянно. Пруф:
https://svodd.ru/?search%5Bquery%5D=https%3A%2F%2Fyandex.ru%2Fsearch%2F%3Ftext%3D&search%5Bmatching%5D=&search%5Bmatching%5D=query_string&search%5Bdictionary%5D=0

Здесь можно походить по ссылкам в комментариях и всё будет наглядно. 
Я к тому, что комментарии не прятались и в поисковики попадали.

**Comment by iprst** [comment]
> Так что яндекс нас точно забаит нас в выдаче)

Пусть банит, это его дело. 

> В общем, наверно, в текущем моменте оставляем как было. Так?

Пока у этого действия не будет ПФУ, мы его делать не будем ))

**Comment by audetv** [comment]
> > браузеры устанавливают туда поиск, т.е. это строка работает как запрос в поисковик, и если не поставить слэш, косую черту после домена, то клиент попадет опять в выдачу яндекс, гугл, в которых ничего нет
> 
> В хроме такое поведение не воспроизводится. С чистого аккаунта, незнакомого с сайтом:
> 

Да, переключил у себя в хроме поиск по умолчанию с яндекса на гугл и теперь нормальное поведение.
А вот в при поиске по умолчанию - яндекс, описанный мной сценарий воспроизводится. В хроме.

**Comment by iprst** [comment]
> Да, переключил у себя в хроме поиск по умолчанию с яндекса на гугл и теперь нормальное поведение.
> А вот в при поиске по умолчанию - яндекс, описанный мной сценарий воспроизводится. В хроме. Такие дела с яндексом)

Вон оно что. Будем знать. Впрочем, что тут знать, про яндекс всё давно понятно.

**Comment by audetv** [comment]
UPD Загоняют к себе в поиск всеми возможными способами. Я пока мы не начали обсуждать про домен ,как то и не задумывался, вижу на работе, что люди вбивают и попадают в поиск, а яндекс у многих по умолчанию стоит. Знаю, что меня подбешивало это поведение, и я ставил слэш намеренно, или выбирал из выпадающего списка, но вот так вот, как мы сейчас в этом issue не формулировал это ранее, выработал стереотип и описал, .зачем это сейчас произошло?)

**Comment by iprst** [comment]
> зачем это сейчас произошло?

Значит вам было пора осознать какой-то элемент мозаики, пришло время, прозвенел горшок, и тд. 
Да, имеет смысл сконцентрироваться далее на насущной повестке.
