### ISSUE TITLE
Проблема двух языков в wordforms

### ISSUE THREAD

**Issue by iprst** [audetv/fct-search#153]
В [wordforms](https://github.com/audetv/conceptual-dictionary/blob/main/manticore/wordforms.txt) добавлена пара английское + русское слово:

`~gaga > гага`

В результате установлено, что поиск слова «гага» по слову 'gaga' не производится, то есть межъязыковые пары [wordforms](https://github.com/audetv/conceptual-dictionary/blob/main/manticore/wordforms.txt), судя по всему, не работают. 

![image](https://user-images.githubusercontent.com/129882753/234647625-8bfc6df6-3c95-485e-aa1d-2281e785004c.png)

При этом поиск в режиме «По совпадению слов» даёт идентичные результаты как с подключением концептуального словаря, так и с отключенным: 

![image](https://user-images.githubusercontent.com/129882753/234652802-ee085b70-c32b-45a9-acdc-ce0229832658.png)

**Comment by audetv** [comment]
> то есть межъязыковые пары [wordforms](https://github.com/audetv/conceptual-dictionary/blob/main/manticore/wordforms.txt), судя по всему, не работают.

Я к такому же выводу пришел, но пока не теряю надежду, просто возможно еще что то не знаем.

**Comment by iprst** [comment]
Можно проверить ещё на одной паре. Добавил в [wordforms](https://github.com/audetv/conceptual-dictionary/blob/main/manticore/wordforms.txt) строки: 

```
Антиохийский > Антиохия
Антиох > Антиохия
Antioch > Антиохия
```
На этот раз без тильды, посмотрим что будет. 

Сейчас совместный поиск слов даёт 41 результат: 

![image](https://user-images.githubusercontent.com/129882753/234661005-6797a6c7-6a4c-4764-8471-4252c78c629c.png)

**Comment by audetv** [comment]
Да, хорошо проверю, и в следующем обновление загружу. 

> На этот раз без тильды, посмотрим что будет.

Gaga без тильды пробовал, и пробовал добавлять в exceptions.txt, но не работало.

**Comment by iprst** [comment]
> Gaga без тильды пробовал, и пробовал добавлять в exceptions.txt, но не работало.

Понял. Тогда возможно нужно сделать небольшой набор рус+англ пар с переменой мест между ними, для проверки и статистики? 

```
UN > ООН
US > США
Ukraine > окраина
гугл > google
яндекс > yandex
```
и тд. 

Добавил, предлагаю пополнять блок рус+англ чтобы выяснить более точно, пока документация и форумы по мантикорне не дочитаны. В любом случае собственный опыт всегда полезен.

**Comment by audetv** [comment]
подключу отдельным файлом

**Comment by audetv** [comment]
Вчера вечером меня укрепило в мысли, что мы просто ещё что-то не знаем, и как-то это должно работать то, что при проверке в консоли состояния (docker mysql) таблицы (текущего v0.2.0 словаря), я получил такой результат:

```
mysql> call keywords('gaga', 'questions_ext');
+------+-----------+-------------+
| qpos | tokenized | normalized  |
+------+-----------+-------------+
| 1    | gaga      | гага        |
+------+-----------+-------------+
mysql>
```
Значит мы на правильном пути, т.е. система приводит к форме, но не показывает. почитал ещё настройки, настройки поиска, потыкал разные ручки, не работало, не помню почему, просто  брутфорс, но снова стал перечитывать статью
https://procodings.ru/dev-ru/formy-slova-protiv-isklyucheniy-v-manticore-search/

И дошел до раздела: 

> Пол и декор
> Рассмотрим другой пример: мы хотим улучшить поиск по названию бренда Floor & Decor. Мы можем предположить, что люди могут писать это название в следующих формах:
```
Floor & Decor
Floor & decor
floor & decor
Floor and Decor
floor and decor
и другие комбинации капитализации букв.
```

И далее: 

> Наиболее оптимальным решением в данном случае будет просто использовать wordforms вот так:
> 
> ➜  ~ cat /tmp/wordforms
> floor & decor => fnd
> floor and decor => fnd
> floor & decor holdings => fnd
> floor and decor holdings => fnd
> floor & decor holdings inc => fnd
> floor and decor holdings inc => fnd

Ага, подумал я и начал тест. Итог.
Я добавил файл alternateforms.txt 
Вписал туда значения, закодировал значения первой формы слова в md5,  получилось так:

```
~gaga > 811584043b844704c9bb9a6e99dd05d3
~Гага > 811584043b844704c9bb9a6e99dd05d3
~Антиох > 14b48136e0afe5bacfa4df688fb72846
~Антиохийский > 14b48136e0afe5bacfa4df688fb72846
~Antioch > 14b48136e0afe5bacfa4df688fb72846
~ООН > 3dac42f7c00184a0091544dee8968c4b
UN > 3dac42f7c00184a0091544dee8968c4b
США > b7e7dfa0bf43a058752addd1eb1e1f47
US > b7e7dfa0bf43a058752addd1eb1e1f47
~окраина > dae2d2894838014ea61eb02efad03f7b
~Ukraine > dae2d2894838014ea61eb02efad03f7b
гугл > fdb12e0e265dd5c7fe5c90518ef92c50
google > fdb12e0e265dd5c7fe5c90518ef92c50
яндекс > d13025ef6d38512f24557f95645447a4
yandex > d13025ef6d38512f24557f95645447a4
```

Теперь работает. Результат:

<details><summary>Details</summary>
<p>

![2023-04-27_11-47-26](https://user-images.githubusercontent.com/10896447/234810692-be045490-0202-4789-9d14-bbf879bf7225.png)

![2023-04-27_11-47-50](https://user-images.githubusercontent.com/10896447/234810706-0a9a1f05-ebed-4377-a9ba-7b45b576e6d1.png)


![2023-04-27_11-48-13](https://user-images.githubusercontent.com/10896447/234810772-ca2189e7-51fa-49c4-b6b6-92667ee2c807.png)

</p>
</details> 

Сегодня обновлю.

**Comment by iprst** [comment]
> Где об этом прочитать в документации? Такое пишут в документации? Ладно, эти вопросы риторические. Задача решена.

Вот так документация и пишется — за счёт крови и пота пользователей и их руками.
