### ISSUE TITLE
Очень медленно загружается сайт

### ISSUE THREAD

**Issue by iprst** [audetv/fct-search#188]
Сегодня, особенно во второй половине дня, сайт через раз отдаёт Gateway Timeout, наиболее часто на странице графика. Браузер и устройство принципиального значения не имеют.

**Comment by audetv** [comment]
Это точно не баг. Я заметил это сейчас вечером примерно около 23:00 по МСК. Днем не загружал сайт, не знаю. После 18:00, сайт работал, я во всяком случае не наблюдал тормозов, а к 23:00 уже заметил. Это что-то у провайдера и это с сетью, канал. Так как во время зависания нельзя было подключиться по ssh к серверу. Сами сервера работают нормально, перегруза нет, тут проблема похоже в каналах связи у провайдера. Буду наблюдать. Не знаю, что можно сделать сейчас в этом случае.

**Comment by iprst** [comment]
Возможно укроп атакует какие-то соседние центры и нагрузка съела канал.

**Comment by audetv** [comment]
> Возможно укроп атакует какие-то соседние центры и нагрузка съела канал.

Возможно, посмотрим, я как заметил то, по всем машинам проверил нагрузку, ее нет. Наблюдаю.

**Comment by audetv** [comment]
Написал в тех поддержку, интересно, что скажут.

**Comment by iprst** [comment]
По времени примерно такой расклад — где-то с 15-16 часов начались перебои, выражаемые в замедлении загрузки страниц, притом любых, не связанных с поиском в базе, но происходило это не постоянно, а обрывочно, через раз или через два. Так продолжалось по-видимому всё время до 22-23 часов, а после этого перебои стали более долгими и постоянными. Смена браузеров, устройств и провайдеров ничего не изменила, то есть это где-то вокруг серверов нашего домена, а не на пользовательской стороне.

**Comment by audetv** [comment]
Вчера общался с тех. поддержкой. сказали, что на их ЦОД атак нет, подсказали как проверить маршруты, сделал трассировку маршрутов, отправил в тп в общем наблюдались потери на маршруте между серверами в МСК СПБ. В общем помогли разобраться, молодцы.

> По предоставленной вами статистики есть потери на 5 хопе при запросах до сервера.
> При запросах с сервера потерь нет
>Рекомендуется проверить корректность работы с другой интернет сети или же используя впн.

Я на неделе завершу переезд . Сейчас ситуация такая, что сервер принимающий запросы (балансировщик nginx) и распределяющий их по сервисам, и парсеры в СПБ, а БД и Мантикора и сайт в МСК, и между ними ходит трафик. Я не хотел делать полный перенос до праздников, так как если будут проблемы после переезда, чтобы не иметь их в праздники. Теперь завершу работы спокойно. Сейчас, вроде, проблем не наблюдается. Работаем.

**Comment by iprst** [comment]
Сейчас всё летает.
