### ISSUE TITLE
В хроме над ссылками в списке тем по событию _mouseover_ курсор не меняется на «палец», то есть не очевидно, что это ссылка. 

### ISSUE THREAD

**Issue by audetv** [audetv/fct-search#56]
В хроме над ссылками в списке тем по событию _mouseover_ курсор не меняется на «палец», то есть не очевидно, что это ссылка. Сам переход по ссылке работает. В других браузерах не смотрел.

_Originally posted by @iprst in https://github.com/audetv/fct-search/issues/55#issuecomment-1501883942_

**Comment by iprst** [comment]
Работает. Между строками видимо нет пространства без mouseover? То есть отслеживаемые пиксели примыкают друг к другу вплотную. Если бы была отбивка 1-2 пикселя, то курсор изменял поведение при переходе между ссылками.

**Comment by audetv** [comment]
Да, между строками нет пространства, контейнеры идут вплотную, наверное можно эмулировать и задать расчетные области и задать между ними расстояние, но вот так с ходу не получилось, и в итоге не захотел на это тратить время, т.к. в общем то над этой областью «палец» появляется и облегчает понимание, что тут ссылки.
