### ISSUE TITLE
Значок, иконка ico для сайта-поиска

### ISSUE THREAD

**Issue by audetv** [audetv/fct-search#76]
Мои варианты просты. Если можно, для проверки примерить, посмотрим как будет выглядеть. 

[favicon_A.zip](https://github.com/audetv/fct-search/files/11236696/favicon_A.zip)

<img src="https://user-images.githubusercontent.com/129882753/232149417-d2b41e20-d56d-4541-86a1-6bfbaab12675.png" width="100" height="100" />

[favicon_B.zip](https://github.com/audetv/fct-search/files/11236697/favicon_B.zip)

<img src="https://user-images.githubusercontent.com/129882753/232149423-68f2ceca-23f6-429f-90f9-468de3ac4524.png" width="100" height="100" />

[favicon_C.zip](https://github.com/audetv/fct-search/files/11236763/favicon_C.zip)

<img src="https://user-images.githubusercontent.com/129882753/232149425-29001286-2040-4d5e-a236-2928f7cc2c3d.png" width="100" height="100" />

Я за нижний вариант.

_Originally posted by @iprst in https://github.com/audetv/fct-search/discussions/74#discussioncomment-5620086_

**Comment by iprst** [comment]
Долгое нажатие ЛКМ с зажатым CTRL — и фавикон обновился. Выглядит хорошо.

![ohof](https://user-images.githubusercontent.com/129882753/232157539-f2dc9da9-7cfa-4d8a-8333-dc3badd34809.png)

Слегка улучшил, подчистил алиазинг на краях и чуть увеличил масштаб:
[favicon_D.zip](https://github.com/audetv/fct-search/files/11237285/favicon_D.zip)

**Comment by audetv** [comment]
Отлично, то что надо, я завтра весь набор размеров иконок и установлю

**Comment by iprst** [comment]
По-моему круто выглядит, надо оставлять. На всякий случай продублирую завтра «золотой» звездой, пусть будет.

**Comment by audetv** [comment]
Обновление прошло. Выглядит отлично.
