### ISSUE TITLE
Тёмная тема для сайта

### ISSUE THREAD

**Issue by iprst** [audetv/fct-search#87]
Очень нужна. На моих ящиках яркий белый цвет делает боль. Подправить дефолтный дизайн не будет проблемой, но требуется подключить переключатель dark / light.

**Comment by audetv** [comment]
Да. 
надо посмотреть этот вариант, https://getbootstrap.com/docs/5.3/customize/color-modes/#dark-mode
подключу и дальше можно настраивать.

**Comment by iprst** [comment]
Отлично. Ещё момент, касается обеих тем — в поисковой строке есть функционал «очистить строку», выполняется кнопкой-крестиком, который вроде как svg файл. Крестик синий под стандартную тему, хотел поменять, но не смог его найти.

**Comment by audetv** [comment]
этот крестик вообще из коробки браузера ))) т.е. это стандартная функция от <input type="search">, он скорее всего сильно спрятан где-то в default секциях f-12,но настроить цвет тоже можно, все настраивается, сделаем. Поищу его.

**Comment by audetv** [comment]
темную тему можно посмотреть как будет, в режиме разработчика f-12 добавить к тэгу html атрибут data-bs-theme="dark"
`<html lang="ru" class="h-100" data-bs-theme="dark">`
предварительно что-нибудь в поиске набрать для показа выдачи.
Надо будет поправить поисковый контейнер, его я сам делал и не работает dark режим на нем. Ну, и так посмотрите, я уже завтра сделаю в меню кнопку переключения режима светлый/темный и будем уже темный настраивать.

**Comment by audetv** [comment]
![2023-04-17_00-19-07](https://user-images.githubusercontent.com/10896447/232343179-e8bcfbf8-f6bb-45dd-bed4-3be334f34fee.png)

**Comment by iprst** [comment]
Да, работает превью в таком режиме. Этого достаточно для правки — страницу можно сохранить и править в оффлайне.

**Comment by audetv** [comment]
Только сейчас понял, что удалил авто режим. Позже добавлю.

**Comment by audetv** [comment]
Я сделал общий файл стилей назвал его red_svodd.css
Закономерность удалось установить такую:
Цвета, которые должны меняться при переключении должны быть переменными var(--name-var)
В секции: 
```
root, [data-bs-theme=light] {
/*Светлая тема красный СВОДД, наши вставки*/
--svodd-breadcrumb: #e9ecef;
}
```
 эти переменные должны присутствовать со значениями цвета для темы светлой.
В секции:

```
[data-bs-theme=dark] {
/*Тёмная тема красный СВОДД, наши вставки*/
--svodd-breadcrumb: #141618;
}
```
эти же переменные должны  присутствуют только со значениями для тёмной темы.

В селекторах, ставим значения переменных так:

```
.breadcrumb {
    background-color: var(--svodd-breadcrumb);
}
```

После этого все корректно работает. Я частично перевел, не весь код в переменные, и убрал лишнее из предыдущих файлов стилей, что мешало. Остальные стили в работе.

**Comment by iprst** [comment]
Понятно, это они сделали для того, чтобы можно было плодить темы оформления практически бесконечно.

**Comment by iprst** [comment]
У вас в тёмной теме наблюдается яркая вспышка после нажатия ввода при поиске или при переходе между «поиском» и «обсуждением»?

**Comment by audetv** [comment]
Наблюдается, но потом пропадает после прохода нескольких страниц, хотя нет, возвращаясь на главную опять вспышка. я пока не понял, что дает этот эффект, надо искать, так нельзя оставлять. На других страницах вроде бы это не набюлдается, только на самой главной

**Comment by audetv** [comment]
Похоже, то сначала формируется страница по умолчанию с белым фоном, а потом с задержкой происходит переключение стилей. Не факт, что так. но похоже. Можно как вариант сделать черный фон по умолчанию и будет черная вспышка) как временное решение, надо это проверить

**Comment by audetv** [comment]
Мне нравится как получилась тёмная тема, теперь на ней сижу) Только обязательно надо со вспышкой разобраться и  убрать и с фиолетовым active menu item на переключении тем

**Comment by iprst** [comment]
Я так понял в стилях есть `tertiary-color` и `emphasis-color` которые могут отвечать за это поведение. Но это не точно.

**Comment by iprst** [comment]
К слову, крестик «стиратель» в строке поиска теперь белого цвета — в тёмной теме его видно, а в светлой теме не видно. Но это ничего, это я сейчас поправлю, поскольку собирался покрасить строку поиска в другой цвет — поработав с поиском некоторое время понял, что нужно поисковую строку выделить цветом из фона, чтобы она визуально отыскивалась быстрее и отличалась бы от заголовка окна. 

Закрываю.
