### ISSUE TITLE
Баг с радиокнопками

### ISSUE THREAD

**Issue by audetv** [audetv/fct-search#88]
Понял. Да, там в шаблоне тоже нужно будет доработать — в событии по нажатию радиокнопки (я его не мог прокликать в хроме, ибо слетает дизайн) есть какие-то переходные цвета синих оттенков, их нужно будет тоже докрасить. Всю палитру в общем надо будет перебрать. 

Ещё баг с радиокнопками — там после события не только слетает подсветка, но и стиль ссылок `bs-link-color`

_Originally posted by @iprst in https://github.com/audetv/fct-search/issues/63#issuecomment-1510476276_

**Comment by iprst** [comment]
Поправка, стиль ссылок слетает не из-за радиокнопок. Я его не перенёс в новый css, он в редактированной версии site.css которую я не загружал. Переношу.

**Comment by audetv** [comment]
да, хорошо

**Comment by iprst** [comment]
Поправил цвета ссылок, добавил покраску для паджинации когда много страниц.
