### ISSUE TITLE
Шаблон тёмной темы неполный

### ISSUE THREAD

**Issue by iprst** [audetv/fct-search#99]
Плохое оформление элементов, у которых светлый фон — футера, блока поиска и навигатора хлебных крошек.

![whatiswhite](https://user-images.githubusercontent.com/129882753/232531138-7bea2c43-9605-450a-a9b9-cc4b3f2ca7a7.png)

_Originally posted by @iprst in https://github.com/audetv/fct-search/issues/96#issuecomment-1511569286_

**Comment by iprst** [comment]
Шаблон обновлён, недоработки устранены.

**Comment by audetv** [comment]
Да, вижу, я сейчас подумаю как эти доработки соединить, темную  и светлую темы, чтобы они не перекрывали друг друга. Файл должен быть в итоге один. Я думаю быстро разберусь, надо посмотреть, занимаюсь
